version: "3"
services:
  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "3000:3000"
    depends_on:
      - team_blue
      - team_red

  team_blue:
    build: ./team-blue
    ports:
      - "3001:3001"

  team_red:
    build: ./team-red
    ports:
      - "3003:3003"
